//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bands_Artists
    {
        public int id_bands_artists { get; set; }
        public int id_artists { get; set; }
        public int id_bands { get; set; }
    
        public virtual Artist Artist { get; set; }
        public virtual Band Band { get; set; }
    }
}
